### ISSUE TITLE
packed_bits in downstream consumers isnt documented

### ISSUE THREAD

**Issue by jacobrosenthal** [twitchyliquid64/usbd-hid#4]
if someone else designs the report, like mousereport, you dont actually know that buttons are supposed to be packed_bits, nor do you know you're hardcoded to only have 3 buttons

This could simply be documented, but seems brittle.

**Comment by twitchyliquid64** [comment]
From what I can gather, the desire is to somehow connect the representation of things in the report (ie: buttons) to the typing, rather than relying on documentation or the users knowledge?

I'm not sure how to do this, as thats semantics about how the data is interpreted rather than a concrete datastructure. But forgetting to add `packed_bits` to the docs was an oversight so I can defs do that?

**Comment by twitchyliquid64** [comment]
Actually I think `packed_bits` is documented? The field attributes are [documented](https://docs.rs/usbd-hid/0.3.7/usbd_hid/descriptor/attr.gen_hid_descriptor.html) after the examples section.

**Comment by jacobrosenthal** [comment]
What im saying is, its impossible to know here that buttons should be the lower 3 bits, not the upper 3, or some other packed method of storage
```
    loop {
        cycle_delay(25 * 1024 * 1024);
        push_mouse_movement(MouseReport{x: 0, y: 4, buttons: 0}).ok().unwrap_or(0);
        cycle_delay(25 * 1024 * 1024);
        push_mouse_movement(MouseReport{x: 0, y: -4, buttons: 0}).ok().unwrap_or(0);
    }
```

**Comment by twitchyliquid64** [comment]
Ahhhh understood, I'll update the documentation to indicate `num_bits` refers to the least significant bits.
